Repository matryer/xbar-plugins, pull requests merged in 2023-05, with the labels that each got.

#1949 feat: ram load plugin
  System/ram-load.5s.py
Labels: chmod, python

#1822 Network latency plugin
  Network/network-latency.5s.py
Labels: python, image update

#1709 My quick-n-dirty new mail counter
  Email/simple-mail-checker.1m.py
Labels: python, image update

#1723 Fixes #1722: Add Acquia Cloud plugins.
  Dev/Acquia/.INSTALL.md
  Dev/Acquia/.acquia-includes.php
  Dev/Acquia/001-acquia-list-apps.1h.php
  Dev/Acquia/001-acquia-list-ides.1h.php
Labels: php, image update

#1687 New plugin for Zendesk tickets
  Web/zendesk.2m.rb
Labels: ruby

#1476 Create getComputerInfo.sh
  System/getComputerInfo.sh
Labels: chmod, shell, image update

#1655 added bluetooth connection indicator
  Network/bluetooth_connection.5s.sh
Labels: chmod, shell, image update

#1535 iTerm SSH Dropdown Menu
  Network/iTermSshMenu.sh
Labels: chmod, shell, image update
