Repository matryer/xbar-plugins, pull requests merged in 2023-01, with the labels that each got.

#1901 Updating plugins to have execute permissions enabled.
  System/Battery/lowbatterymode.1h.sh
  System/swap-usage.1m.sh
  Web/counttabs.5m.sh
Labels: chmod

#1713 resolve 001-gasnow.10s.sh: #1711
  Cryptocurrency/Ethereum/gasnow.10s.sh
Labels: shell

#1708 Find all the tags instead of '[firsttag', as currently.
  Time/watson.1m.sh
Labels: shell

#1707 Added fb-dns plugin
  Web/fb-dns/001-fb_dns.5s.sh
  Web/fb-dns/LICENSE
  Web/fb-dns/README.md
  Web/fb-dns/screen-shot.png
Labels: shell

#1726 Add decimal variable
  Cryptocurrency/Monero/monero-usd-kraken.30s.sh
Labels: shell

#1741 Fix brew path on arm64 macs
  Dev/Homebrew/brew-updates.1h.sh
Labels: shell

#1877 Update for WC 2022
  Sports/worldcup.1m.php
Labels: php

#1641 Add a Netatmo plugin
  Weather/netatmo.5m.go
Labels: go

#1809 Update yabai/skhd helper for yabai 4.0.0+
  Tools/yabai_skhd.1s.sh
Labels: shell

#1808 real-cpu-usage-chart spark fix for M1 mac homebrew
  System/real-cpu-usage-chart.10s.sh
Labels: shell

#1599 Updating and Maintaining Pastebin Checker
  Dev/Pastebin/pastebin.1m.sh
  Dev/Pastebin/pastebin.3m.sh
Labels: shell

#1743 Upgrade NTFS Mounter to v1.1
  System/ntfs.1d.sh
Labels: shell

#1745 remove dependencies and enhance the UX of the Air Quality Index plugin.
  Weather/aqi.15m.sh
Labels: shell

#1772 Add plugin to monitor jenkins agent status
  Dev/Jenkins/jenkins-agent-status.5m.sh
Labels: shell

#1597 GCP project switcher plugin
  Cloud/GCP/gcp-project-switcher.1d.sh
Labels: shell

#1779 Update gmail-checker.sh
  Email/gmail-checker.sh
Labels: shell

#1638 Update pagerduty.30s.rb
  Tools/PagerDuty/pagerduty.30s.rb
Labels: ruby

#1770 Add Ethereum and Polygon gas fee plugin
  Cryptocurrency/Ethereum/eth_gas_widget.10m.rb
  Cryptocurrency/Polygon/polygon_gas_widget.10m.rb
Labels: ruby

#1598 Update Foobot.10b plugin to use xbar.var for API_KEY and DEVICE_ID
  Weather/Foobot.10m.rb
Labels: ruby

#1841 Update Web/feedly.rb
  Web/feedly.rb
Labels: ruby

#1806 Update slack-team-notifications.1m.js to v1.1.3
  Tools/Slack/slack-team-notifications.1m.js
Labels: node

#1699 Create brewfather-batch-status.15m.js
  Lifestyle/brewfather-batch-status.15m.js
Labels: node

#1865 Update Lifestyle/Todo/NotePlan
  Lifestyle/Todo/NotePlan3.15m.rb
Labels: ruby, image update, bitbar

#1656 Add support for Mempool.space
  Cryptocurrency/Bitcoin/mempool.sh
  Cryptocurrency/mempool.space
Labels: shell, image update

#1480 Add a simple latency check
  Network/simple-latency.11s.sh
Labels: shell, image update

#1460 Add mintable.1h.zh plugin
  Finance/mintable.1h.zsh
Labels: chmod, shell, image update, bitbar

#1783 Add plugin for podman
  Dev/podman.5s.sh
Labels: shell, image update

#1788 Add new plugin: evcc (solar ev charging)
  IoT/evcc.10s.rb
Labels: ruby, image update

#1445 Wakatime plugin
  Dev/Wakatime/wakatime.1m.js
Labels: node, image update, bitbar

#1679 Added super basic WLED plugin
  IoT/wled.1m.js
Labels: node, image update

#1752 Add new plugin for github version of gitlab_merge_requests.js
  Dev/GitHub/github_work_list.1m.mjs
Labels: node, image update

#1848 Update SureFlap plugin for xbar
  Lifestyle/sureflap.15s.rb
Labels: ruby, image update

#1448 add fan_speed plugin for newer model
  System/fan_speed.5s.js
Labels: node, bitbar

#1899 Update GitHub status icon
  Dev/GitHub/github_status.10m.py
Labels: python

#1747 Fix shell cmd
  Music/sonosBar.py
Labels: python

#1750 Update weather.15m.py
  Weather/weather.15m.py
Labels: python

#1895 Fix Homebridge plug-in
  IoT/homebridge.10s.py
Labels: python

#1870 Update GitLab Glance plugin
  Dev/Gitlab/gitlab_glance.15m.py
Labels: python

#1832 Update live_tennis.1m.py
  Sports/live_tennis.1m.py
Labels: python

#1818 Replace icon placeholders with real emojis
  Weather/DarkSky/weather.15m.py
Labels: python

#1784 Fix for okex_ticker.10s.py: OKEx changed their domain and API
  Cryptocurrency/okx_ticker.10s.py
Labels: python

#1782 Updated documentation for github-review-requests.5m.py
  Dev/GitHub/github-review-requests.5m.py
Labels: python

#1694 Better error handling
  Travel/commuter.365d.py
Labels: python

#1803 showhide-files plugin: add python3 compatibility
  System/showhide-files.1d.py
Labels: python

#1813 fix shebang & spaces in script path
  Music/sonosBar.py
Labels: python

#1816 Upgrade to Meta Package Manager plugin v5.5.1
  Dev/meta_package_manager.7h.py
Labels: python

#1693 Add Scaleway instance management plugin
  Cloud/scaleway.sh
Labels: shell, homebrew dep

#928 Monitor radiation from a uRadMonitor device
  network/uRadMonitor.30s.sh
Labels: shell, image update

#1463 Add Buildkite plugin
  Dev/Buildkite/buildkite.1m.sh
Labels: shell, bitbar

#1658 Add feature-filled Nagios plugin
  Dev/Nagios/nagios.30s.sh
Labels: shell

#1659 Add Pagerduty plugin
  Tools/PagerDuty/pagerduty_incidents.1m.sh
Labels: shell

#1657 Initial add of the wol plugin
  Tools/wol/wol-nas.10s.sh
Labels: shell

#1669 Add plugin to toggle wifi when laptop lid gets opened/closed
  Network/wifi-toggle-by-lid.sh
Labels: shell

#1746 Updated Api Source
  Cryptocurrency/Ethereum/gasnow.10s.sh
Labels: shell

#1903 Add uptime-kuma plugin
  Dev/uptimekuma.30s.py
Labels: python

#1902 Python3 update
  Lifestyle/deathTimer.5m.py
Labels: python

#1894 Use consistent Python 3 shebang
  AWS/cloudwatch-alarms.30s.py
  CONTRIBUTING.md
  Cryptocurrency/Bitcoin/tr-markets.1m.py
  Cryptocurrency/Ethereum/eth_wallet_balances.1m.py
  Cryptocurrency/Ethereum/ethminer.5s.py
  Cryptocurrency/cardano.10s.py
  Cryptocurrency/coincap.1m.py
  Cryptocurrency/coincaplite.1m.py
  Dev/Gitlab/gitlab_glance.15m.py
  Dev/Jira/jira-issues.10m.py
  Dev/Nagios/thruk.py
  Dev/noti.1m.py
  E-Commerce/nvidia.3m.py
  Environment/CO2-Signal.10m.py
  Finance/hours.1m.py
  Finance/robinhood2.1m.py
  Finance/yahoo_stock_ticker.10m.py
  IoT/BMWcharge.15m.py
  Lifestyle/zoom_onair.15s.py
  Music/ksing.1d.py
  Science/apod.1h.py
  Sports/bundesliga.1h.py
  Sports/fcbarcelona-dk.1h.py
  Sports/live_nba.1m.py
  System/DoNotDisturb.1s.py
  Weather/weather.15m.py
  Weather/yahoo-weather.5m.py
  Web/ProductHunt/producthunt-tech-hunts.1d.py
  Web/bilibili.py
  Web/bitbar-uptime_robot.py
  Web/putio.5m.py
  Web/todays_tweets.30m.py
  Web/wanikani.15m.py
Labels: python

#1892 Update Add Note for Python 3
  Tools/addnote.5s.py
Labels: python

#1766 add zoom shortcuts plugin
  Lifestyle/zoom_shortcuts.1d.sh
Labels: chmod, shell

#1886 Add 'Who's Home? (for UniFi)'
  Tools/whos-home-unifi.1m.py
Labels: python

#1891 Migrate plug-ins to Python 3
  Cryptocurrency/99-crypto.py
  Cryptocurrency/Bitcoin/bitx.co/buy-and-sell.1m.py
  Cryptocurrency/Bitcoin/coinmarketcap.com/btc-gbp.py
  Cryptocurrency/Bitcoin/coinmarketcap.com/btc-usd.py
  Cryptocurrency/Bitcoin/coinone.co.kr/coinone.15s.py
  Cryptocurrency/Blackcoin/blk-gbp.py
  Cryptocurrency/Blackcoin/blk-usd.py
  Cryptocurrency/Dogecoin/doge-gbp.py
  Cryptocurrency/Dogecoin/doge-usd.py
  Cryptocurrency/Ethereum/eth-gbp.py
  Cryptocurrency/Ethereum/eth-usd.1s.py
  Cryptocurrency/Lisk/lsk-gbp.py
  Cryptocurrency/Lisk/lsk-usd.py
  Cryptocurrency/Litecoin/ltc-gbp.py
  Cryptocurrency/Litecoin/ltc-usd.1s.py
  Cryptocurrency/Ripple/xrp-gbp.py
  Cryptocurrency/Ripple/xrp-usd.py
  Cryptocurrency/binance-ticker.6s.py
  Cryptocurrency/guild.1m.py
  Dev/GitHub/github_status.10m.py
  Dev/circleci-check.5m.py
  Dev/gosquared-now.30s.py
  Finance/awin-sales.60s.py
  Finance/stock-ticker.30s.py
  Finance/transferwise-currency-tracker.1m.py
  Lifestyle/digital-zeitgebers.30m.py
  Lifestyle/githubzen.1m.py
  Lifestyle/memento_mori.py
  Lifestyle/text_on_menubar.1h.py
  Lifestyle/todoist.1m.py
  Music/quodlibet-control.1s.py
  Music/songkick.1d.py
  Network/pi-hole.10m.py
  Network/protonvpn.15m.py
  Politics/parliament.uk-count.5m.py
  Sports/live_tennis.1m.py
  System/battery_health.2s.py
  System/keyboard-symbol.py
  System/memusage.5s.py
  System/screenshot.1d.py
  System/show-hide-desktop-icons.1h.py
  System/usbInfo.10s.py
  Time/age-ticker.1s.py
  Time/countdown.1s.py
  Time/countdown_timer_2.1s.py
  Time/fuzzyclock.1s.py
  Time/itstimeto.15m.py
  Time/prayer-time.1m.py
  Time/solar-time.1s.py
  Time/spent_time.1s.py
  Travel/commuter.365d.py
  Web/Reddit/reddit.1m.py
  Web/YouTube/subgap.1s.py
Labels: python

#1833 Add Github PR status plugin
  Dev/GitHub/github-pr-buddy.30m.py
Labels: python

#1869 Add Github Release buddy
  Dev/GitHub/github-release-buddy.30m.py
Labels: python

#1872 Add AWS CodePipeline Status plugin pipeline-status.1m.py
  AWS/pipeline-status.1m.py
Labels: python

#1739 Crypto Miner statistic fetcher
  Cryptocurrency/miner_stat_fetch.1m.py
Labels: python, image update

#1697 Add new plugin Quran Daily
  Lifestyle/qurandaily.1d.py
Labels: python

#1686 Add yabai-viewer plugin
  Tools/yabai-viewer.1s.py
Labels: python

#1671 Fetch crypto from coinmarketcap with your own filters
  Cryptocurrency/coinmarketcap.30m.py
Labels: python

#1502 Added docker plugin
  Tools/bitbarDockerContainers.1m.py
Labels: python

#1440 Create weather.1h.py
  Weather/weather.1h.py
Labels: python

#1749 Add new plugin: jackpot
  Games/jackpot.6h.py
Labels: python, image update

#1839 add zoom_mute plugin
  Lifestyle/zoom_mute.3s.sh
Labels: shell, image update

#1758 added Ethereum EIP1559 base fee plugin
  Cryptocurrency/Ethereum/eth_basefee.30s.sh
Labels: shell

#1842 Updated ec2-start-stop plugin
  AWS/ec2-start-stop.1h.sh
Labels: shell

#1896 Add weather script using DarkySky drop-in replacement PirateWeather.net
  Weather/DarkSky/weather.15m.sh
  Weather/pirate_weather.15.py
Labels: python

#1715 feat: new brew-updates plugin which also replaces homebrewcask plugin
  Dev/Homebrew/brew-updates.1h.rb
  Dev/Homebrew/brew-updates.1h.sh
  Dev/Homebrew/homebrewcask.1d.sh
Labels: ruby

#1717 feat: rewrite brew-services plugin
  Dev/Homebrew/brew-services.10m.rb
Labels: ruby

#1759 add hot search list of Weibo
  Web/weibo.1h.py
Labels: python, image update

#1446 Add unmount plugin for unmounting/ejecting volumes
  System/unmount.10.js
Labels: node, bitbar

#1907 Add LibreLinkUp Plugin
  Lifestyle/librelinkup.1m.py
Labels: chmod, python, image update
