Repository matryer/xbar-plugins, pull requests merged in 2023-04, with the labels that each got.

#1871 Add Azure DevOps plugin build-status.1m.js
  Dev/AzureDevOps/build-status.1m.js
Labels: node, image update

#1938 LibreLinkUp - some Cleanup and high/low display color fix
  Lifestyle/librelinkup.1m.py
Labels: python

#1927 feat(Dev/Homebrew/brew-updates): new options and style changes
  Dev/Homebrew/brew-updates.1h.rb
Labels: ruby

#1926 feat(Dev/Homebrew/brew-services): improve settings and style
  Dev/Homebrew/brew-services.10m.rb
Labels: ruby

#1937 Add Zoom Audio/Video/Share Status plugin
  Lifestyle/zoom-avs-status.1s.scpt
Labels: chmod, bitbar

#1771 Made a plugin to replace the one using gasnow.org since its gone down…
  Cryptocurrency/Ethereum/ethgas.1m.sh
Labels: shell, image update

#1941 Added Zerotier Status Plugin
  Network/zerotier-status.1s.py
Labels: chmod, python

#1765 Adds airspace.5m.py plugin to /travel
  Travel/airspace.5m.py
Labels: chmod, python

#1677 Add IPs plugin to show local and external IP
  Dev/ips.30s.sh
Labels: chmod, shell

#1532 Journaling with The Archive
  Lifestyle/journal.sh
Labels: chmod, shell, bitbar

#1425 New plugin
  Time/DayAndNightClock
Labels: chmod, shell, bitbar

#1353 rclone-mount
  Tools/rclone-mount.1m.sh
Labels: chmod, bitbar

#1936 Add Beeminder (for single goal)
  Web/beeminder_one_goal.1m.py
Labels: python

#1740 Added Mullvad VPN Status checker
  Network/mullvad-vpn-status.5m.sh
Labels: chmod, shell, image update

#1700 feat: script to show epoch time, comma separated
  Time/epoch.60s.sh
Labels: shell, homebrew dep

#1706 Create plausible.io plugin
  Web/plausible-stats.1m.js
Labels: node, image update
