Repository matryer/xbar-plugins, pull requests merged in 2023-09, with the labels that each got.

#1791 Secure TOTP
  System/secure-totp.sh
Labels: shell, image update

#1986 Add files via upload
  System/battery_estimator.5s.sh
Labels: chmod, image update

#1990 Add a mute / unmute mic plugin
  System/MicToggle.1s.sh
Labels: shell
