Repository matryer/xbar-plugins, pull requests merged in 2023-02, with the labels that each got.

#1810 New plugging to check unread emails from any IMAP mailbox
  Email/imap.1m.rb
Labels: ruby, image update

#1855 Add DevToolbox plugin 🛠
  Tools/dev-toolbox.1h.sh
Labels: shell

#1844 Github-review-request overhaul (powered by TS)
  Dev/GitHub/github-review-requests-TS-5m.ts
Labels: deno

#1882 Add Colima controller
  Dev/colima.10s.sh
Labels: shell

#956 [plugin] GitLab CI Pipeline status
  Dev/Gitlab/gitlab-ci-status.5s.sh
Labels: shell, bitbar

#1755 MacOS OpenVPN and DNS Manager
  Network/openvpn.5m.sh
Labels: shell, homebrew dep, bitbar

#1887 Add Productivity Countdowns plugin
  Time/productivitycountdowns.1h.sh
Labels: chmod, shell

#1916 Fix toggl workflow
  Web/toggl.1m.js
Labels: node

#1913 Create Colima-status.2s.zsh
  Dev/colima-status.2s.sh
Labels: chmod, shell, image update

#1917 Update colima-status.2s.sh
  Dev/colima-status.2s.sh
Labels: shell

#1918 Issue #1911: New Plugin request - power-wattage-advanced.sh
  System/power-wattage-advanced.30m.sh
Labels: shell

#1919 Cryptocurrency / Solana Price Ticker
  Cryptocurrency/Solana/Solana_Price_Ticker.30s.py
Labels: chmod, python

#1921 Update Homebrew plugins to fix issue on Apple Silicon Macs and add Greedy option
  Dev/Homebrew/brew-services.10m.rb
  Dev/Homebrew/brew-updates.1h.rb
Labels: ruby

#1920 Add CheckSuite image and href
  Dev/GitHub/notifications.30s.py
Labels: python
