Repository matryer/xbar-plugins, pull requests merged in 2024-02, with the labels that each got.

#2023 Add eth_all_in_one.5s.sh plugin
  Cryptocurrency/Ethereum/eth_all_in_one.5s.sh
Labels: chmod, shell, image update

#2025 sunrise-sunset: create the sun indicator
  Weather/sunrise-sunset/LICENSE
  Weather/sunrise-sunset/README.md
  Weather/sunrise-sunset/sun-full.png
  Weather/sunrise-sunset/sun-indicator.png
  Weather/sunrise-sunset/sun.1m.py
Labels: python

#2026 Fixed an issue where IPv6 addresses would incorrectly show iCloud Private Relay as active
  Network/iCloud-Private-Relay-Status.6m.sh
Labels: shell

#2027 Toggl time-tracking software, hours for the week
  Time/toggl.10m.sh
Labels: shell
