Repository matryer/xbar-plugins, pull requests merged in 2024-01, with the labels that each got.

#2006 Live Tennis: Adapted to new API changes in ATP website
  Sports/live_tennis.1m.py
Labels: python

#2008 Live Cricket: Adapted to new API changes in Cricinfo website
  Sports/live_cricket.2m.py
Labels: python

#2009 added leetcode_reminder
  Web/leetcode_reminder.5m.py
Labels: python

#1721 Add Helium Hotspot aggregator
  Cryptocurrency/Helium/helium-hotspot-rewards.15m.js
Labels: node, image update

#1718 Add Swinsian plugin
  Music/swinsian.10s.sh
Labels: shell, image update

#1630 Cryptocompare portfolio holdings
  Cryptocurrency/cryptocompare-portfolio.1m.rb
Labels: ruby, image update

#1421 Tracking Congress (First plugin using R)
  Politics/congress.1h.R
Labels: image update, rscript

#1553 Add USCIS_CaseStatusUpdates.15m.sh plugin
  Lifestyle/USCIS_CaseStatusUpdates.15m.sh
Labels: shell, image update

#1619 Added Kaiten Dashboard plugin
  Dev/Kaiten/kaiten-dashboard.5m.sh
Labels: shell, image update

#2017 wordle game added
  Games/wordle.py
Labels: python

#2018 Upgrade to Meta Package Manager plugin v5.14.1
  Dev/meta_package_manager.7h.py
Labels: python

#2019 add vars to nightscout and API Token
  Lifestyle/nightscout.1m.sh
Labels: shell

#1795 Newoptionsquoteplugin
  Finance/001-options.1h.go
Labels: chmod, go

#1277 Home Assistant
  Weather/homeassistant.py
Labels: chmod, python, image update
