Repository matryer/xbar-plugins, pull requests merged in 2025-01, with the labels that each got.

#2077 Updated NugetDownloadCount
  Dev/NugetDownloadCount.5h.py
Labels: python

#2078 Update "LibreLinkUp Status" because API to get data changed
  Lifestyle/librelinkup.1m.py
Labels: python

#2080 Adding new plugin for status display and control of Macos VPN profiles
  Network/vpn-next.2s.sh
Labels: shell

#2079 Add Carbon Intensity plugin for monitoring grid cleanliness
  Environment/carbon-intensity.1h.js
Labels: chmod, node

#2081 Updated version v1.1 of Network/vpn-next plugin
  Network/vpn-next.2s.sh
Labels: shell

#2084 Add Lastpass plugin
  System/lastpass.py
Labels: python, image update
