Repository matryer/xbar-plugins, pull requests merged in 2025-04, with the labels that each got.

#2103 new plugin: AWS profile switcher
  AWS/profile-changer.1s.sh
Labels: shell

#2102 Add Homecoming Countdown plugin
  personal/homecoming.1d.sh
Labels: shell

#2092 adding a new plugin to monitor AWS ASGs
  AWS/asg-status.5m.sh
Labels: shell, image update

#2099 Displays BTC, LTC, ETH, XRP and BCH prices from Bitso either in USD or MXN
  Cryptocurrency/bitso-prices.10s.sh
Labels: chmod, shell

#2100 Add AeroSpace Viewer plugin
  Tools/aerospace-viewer.5s.sh
Labels: shell, image update
