Repository matryer/xbar-plugins, pull requests merged in 2025-03, with the labels that each got.

#2083 Release version 1.3
  Environment/carbon-intensity.15m.js
Labels: node, image update

#2097 Lastpass safety enhancement
  System/lastpass.py
Labels: python

#2098 feat: creates `memory_pressure.20s.py` to display system memory pressure
  System/memory_pressure.20s.py
Labels: python, image update
